### ISSUE TITLE
solidity: issue with z3 compatibility

### ISSUE THREAD

**Issue by q9f** [phnx47/pkgbuilds#18]
`solidity` requires a strict `z3` version. currently, building `solidity` on Arch Linux fails with:

```
[ 99%] Linking CXX executable yul-phaser
/usr/bin/ld.gold: pack-relative-relocs: unknown -z option
/usr/bin/ld.gold: use the --help option for usage information
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/yul-phaser.dir/build.make:109: tools/yul-phaser] Error 1
make[1]: *** [CMakeFiles/Makefile2:641: tools/CMakeFiles/yul-phaser.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

It is possible to disable `z3` completely by setting `-DUSE_Z3=OFF` but I don't know if this is the best option as some users might want this.

However, I would prefer not to pin `z3`.

**Comment by phnx47** [comment]
@q9f Thanks for information! `z3` is optional, I prefer not to do any fixes right now and wait fix from upstream.

**Comment by phnx47** [comment]
@q9f I disowned this package, I do not have the necessary skills to support it.
